// Extended sticker library with 15 categories including a massive Daily pack
export const EXTENDED_STICKERS = [
  // ── Daily Emojis (Most commonly used on phones daily) ───
  { id: 'dy1', emoji: '😂', category: 'daily' },
  { id: 'dy2', emoji: '😭', category: 'daily' },
  { id: 'dy3', emoji: '🥺', category: 'daily' },
  { id: 'dy4', emoji: '🔥', category: 'daily' },
  { id: 'dy5', emoji: '💀', category: 'daily' },
  { id: 'dy6', emoji: '🤣', category: 'daily' },
  { id: 'dy7', emoji: '👍', category: 'daily' },
  { id: 'dy8', emoji: '🙏', category: 'daily' },
  { id: 'dy9', emoji: '❤️', category: 'daily' },
  { id: 'dy10', emoji: '✨', category: 'daily' },
  { id: 'dy11', emoji: '👀', category: 'daily' },
  { id: 'dy12', emoji: '🥰', category: 'daily' },
  { id: 'dy13', emoji: '😍', category: 'daily' },
  { id: 'dy14', emoji: '😊', category: 'daily' },
  { id: 'dy15', emoji: '🤔', category: 'daily' },
  { id: 'dy16', emoji: '😉', category: 'daily' },
  { id: 'dy17', emoji: '🥳', category: 'daily' },
  { id: 'dy18', emoji: '😎', category: 'daily' },
  { id: 'dy19', emoji: '🤩', category: 'daily' },
  { id: 'dy20', emoji: '🙄', category: 'daily' },
  { id: 'dy21', emoji: '😴', category: 'daily' },
  { id: 'dy22', emoji: '🥵', category: 'daily' },
  { id: 'dy23', emoji: '🥶', category: 'daily' },
  { id: 'dy24', emoji: '🤡', category: 'daily' },
  { id: 'dy25', emoji: '💩', category: 'daily' },
  { id: 'dy26', emoji: '💯', category: 'daily' },
  { id: 'dy27', emoji: '🎉', category: 'daily' },
  { id: 'dy28', emoji: '🎈', category: 'daily' },
  { id: 'dy29', emoji: '⚡', category: 'daily' },
  { id: 'dy30', emoji: '🌈', category: 'daily' },
  { id: 'dy31', emoji: '🍕', category: 'daily' },
  { id: 'dy32', emoji: '🍔', category: 'daily' },
  { id: 'dy33', emoji: '🍟', category: 'daily' },
  { id: 'dy34', emoji: '☕', category: 'daily' },
  { id: 'dy35', emoji: '🍻', category: 'daily' },
  { id: 'dy36', emoji: '🐱', category: 'daily' },
  { id: 'dy37', emoji: '🐶', category: 'daily' },
  { id: 'dy38', emoji: '🦄', category: 'daily' },
  { id: 'dy39', emoji: '🧸', category: 'daily' },
  { id: 'dy40', emoji: '🎀', category: 'daily' },
  { id: 'dy41', emoji: '💸', category: 'daily' },
  { id: 'dy42', emoji: '✈️', category: 'daily' },
  { id: 'dy43', emoji: '🌍', category: 'daily' },
  { id: 'dy44', emoji: '🌞', category: 'daily' },
  { id: 'dy45', emoji: '🌙', category: 'daily' },
  { id: 'dy46', emoji: '🌧️', category: 'daily' },
  { id: 'dy47', emoji: '❄️', category: 'daily' },
  { id: 'dy48', emoji: '🍀', category: 'daily' },

  // ── Hearts ──────────────────────────────────────────────
  { id: 'h1', emoji: '❤️', category: 'hearts' },
  { id: 'h2', emoji: '🩷', category: 'hearts' },
  { id: 'h3', emoji: '💜', category: 'hearts' },
  { id: 'h4', emoji: '💙', category: 'hearts' },
  { id: 'h5', emoji: '🤍', category: 'hearts' },
  { id: 'h6', emoji: '💕', category: 'hearts' },
  { id: 'h7', emoji: '💝', category: 'hearts' },
  { id: 'h8', emoji: '💖', category: 'hearts' },
  { id: 'h9', emoji: '💗', category: 'hearts' },
  { id: 'h10', emoji: '🫀', category: 'hearts' },

  // ── Stars ───────────────────────────────────────────────
  { id: 's1', emoji: '⭐', category: 'stars' },
  { id: 's2', emoji: '✨', category: 'stars' },
  { id: 's3', emoji: '🌟', category: 'stars' },
  { id: 's4', emoji: '💫', category: 'stars' },
  { id: 's5', emoji: '🌙', category: 'stars' },
  { id: 's6', emoji: '☀️', category: 'stars' },
  { id: 's7', emoji: '🌈', category: 'stars' },
  { id: 's8', emoji: '⚡', category: 'stars' },

  // ── Flowers ─────────────────────────────────────────────
  { id: 'fl1', emoji: '🌸', category: 'flowers' },
  { id: 'fl2', emoji: '🌷', category: 'flowers' },
  { id: 'fl3', emoji: '🌻', category: 'flowers' },
  { id: 'fl4', emoji: '🌹', category: 'flowers' },
  { id: 'fl5', emoji: '🌼', category: 'flowers' },
  { id: 'fl6', emoji: '🪷', category: 'flowers' },
  { id: 'fl7', emoji: '🌺', category: 'flowers' },
  { id: 'fl8', emoji: '🍀', category: 'flowers' },

  // ── Sparkles ────────────────────────────────────────────
  { id: 'sp1', emoji: '🎆', category: 'sparkles' },
  { id: 'sp2', emoji: '🎇', category: 'sparkles' },
  { id: 'sp3', emoji: '✴️', category: 'sparkles' },
  { id: 'sp4', emoji: '🔮', category: 'sparkles' },
  { id: 'sp5', emoji: '💎', category: 'sparkles' },
  { id: 'sp6', emoji: '🫧', category: 'sparkles' },
  { id: 'sp7', emoji: '❄️', category: 'sparkles' },
  { id: 'sp8', emoji: '🌊', category: 'sparkles' },

  // ── Kawaii ──────────────────────────────────────────────
  { id: 'k1', emoji: '🎀', category: 'kawaii' },
  { id: 'k2', emoji: '🍭', category: 'kawaii' },
  { id: 'k3', emoji: '🍬', category: 'kawaii' },
  { id: 'k4', emoji: '🧸', category: 'kawaii' },
  { id: 'k5', emoji: '🎠', category: 'kawaii' },
  { id: 'k6', emoji: '🎡', category: 'kawaii' },
  { id: 'k7', emoji: '🧁', category: 'kawaii' },
  { id: 'k8', emoji: '🍰', category: 'kawaii' },
  { id: 'k9', emoji: '🌙', category: 'kawaii' },
  { id: 'k10', emoji: '🦄', category: 'kawaii' },

  // ── Retro ───────────────────────────────────────────────
  { id: 'r1', emoji: '📻', category: 'retro' },
  { id: 'r2', emoji: '🎵', category: 'retro' },
  { id: 'r3', emoji: '📼', category: 'retro' },
  { id: 'r4', emoji: '🎞️', category: 'retro' },
  { id: 'r5', emoji: '📷', category: 'retro' },
  { id: 'r6', emoji: '🕹️', category: 'retro' },
  { id: 'r7', emoji: '💾', category: 'retro' },
  { id: 'r8', emoji: '📟', category: 'retro' },

  // ── Sunglasses / Face ───────────────────────────────────
  { id: 'g1', emoji: '😎', category: 'sunglasses' },
  { id: 'g2', emoji: '🥸', category: 'sunglasses' },
  { id: 'g3', emoji: '🤩', category: 'sunglasses' },
  { id: 'g4', emoji: '🥳', category: 'sunglasses' },
  { id: 'g5', emoji: '😜', category: 'sunglasses' },
  { id: 'g6', emoji: '🤪', category: 'sunglasses' },
  { id: 'g7', emoji: '😏', category: 'sunglasses' },
  { id: 'g8', emoji: '🫦', category: 'sunglasses' },
  { id: 'g9', emoji: '😍', category: 'sunglasses' },
  { id: 'g10', emoji: '😭', category: 'sunglasses' },

  // ── Tape / Aesthetic ────────────────────────────────────
  { id: 't1', emoji: '📌', category: 'tape' },
  { id: 't2', emoji: '🪄', category: 'tape' },
  { id: 't3', emoji: '🎗️', category: 'tape' },
  { id: 't4', emoji: '🧷', category: 'tape' },
  { id: 't5', emoji: '📎', category: 'tape' },
  { id: 't6', emoji: '🗒️', category: 'tape' },
  { id: 't7', emoji: '📮', category: 'tape' },
  { id: 't8', emoji: '🔖', category: 'tape' },

  // ── Birthday ────────────────────────────────────────────
  { id: 'b1', emoji: '🎂', category: 'birthday' },
  { id: 'b2', emoji: '🎉', category: 'birthday' },
  { id: 'b3', emoji: '🎊', category: 'birthday' },
  { id: 'b4', emoji: '🎁', category: 'birthday' },
  { id: 'b5', emoji: '🎈', category: 'birthday' },
  { id: 'b6', emoji: '🪅', category: 'birthday' },
  { id: 'b7', emoji: '🍾', category: 'birthday' },

  // ── Wedding ─────────────────────────────────────────────
  { id: 'w1', emoji: '💍', category: 'wedding' },
  { id: 'w2', emoji: '💐', category: 'wedding' },
  { id: 'w3', emoji: '🕊️', category: 'wedding' },
  { id: 'w4', emoji: '🥂', category: 'wedding' },
  { id: 'w5', emoji: '🎩', category: 'wedding' },
  { id: 'w6', emoji: '💒', category: 'wedding' },
  { id: 'w7', emoji: '🌹', category: 'wedding' },

  // ── Festival ────────────────────────────────────────────
  { id: 'fes1', emoji: '🪔', category: 'festival' },
  { id: 'fes2', emoji: '🎆', category: 'festival' },
  { id: 'fes3', emoji: '🎋', category: 'festival' },
  { id: 'fes4', emoji: '🎑', category: 'festival' },
  { id: 'fes5', emoji: '🎍', category: 'festival' },
  { id: 'fes6', emoji: '🎏', category: 'festival' },
  { id: 'fes7', emoji: '🧧', category: 'festival' },

  // ── Anime ───────────────────────────────────────────────
  { id: 'a1', emoji: '⛩️', category: 'anime' },
  { id: 'a2', emoji: '🍜', category: 'anime' },
  { id: 'a3', emoji: '🗾', category: 'anime' },
  { id: 'a4', emoji: '🧿', category: 'anime' },
  { id: 'a5', emoji: '🏮', category: 'anime' },
  { id: 'a6', emoji: '⚔️', category: 'anime' },

  // ── Food & Drink ────────────────────────────────────────
  { id: 'fd1', emoji: '🍎', category: 'food' },
  { id: 'fd2', emoji: '🍓', category: 'food' },
  { id: 'fd3', emoji: '🍑', category: 'food' },
  { id: 'fd4', emoji: '🍋', category: 'food' },
  { id: 'fd5', emoji: '🍒', category: 'food' },
  { id: 'fd6', emoji: '🍟', category: 'food' },
  { id: 'fd7', emoji: '🍕', category: 'food' },
  { id: 'fd8', emoji: '🍩', category: 'food' },
  { id: 'fd9', emoji: '🧁', category: 'food' },
  { id: 'fd10', emoji: '🧋', category: 'food' },

  // ── Animals ──────────────────────────────────────────────
  { id: 'an1', emoji: '🐱', category: 'animals' },
  { id: 'an2', emoji: '🐶', category: 'animals' },
  { id: 'an3', emoji: '🐰', category: 'animals' },
  { id: 'an4', emoji: '🦊', category: 'animals' },
  { id: 'an5', emoji: '🐻', category: 'animals' },
  { id: 'an6', emoji: '🐼', category: 'animals' },
  { id: 'an7', emoji: '🐨', category: 'animals' },
  { id: 'an8', emoji: '🦁', category: 'animals' },
  { id: 'an9', emoji: '🐹', category: 'animals' },
  { id: 'an10', emoji: '🐣', category: 'animals' },
];

export const EXTENDED_STICKER_CATEGORIES = [
  { id: 'daily',      label: 'Daily',      icon: '📱' },
  { id: 'hearts',     label: 'Hearts',     icon: '❤️' },
  { id: 'stars',      label: 'Stars',      icon: '⭐' },
  { id: 'flowers',    label: 'Flowers',    icon: '🌸' },
  { id: 'sparkles',   label: 'Sparkles',   icon: '✨' },
  { id: 'kawaii',     label: 'Kawaii',     icon: '🎀' },
  { id: 'retro',      label: 'Retro',      icon: '📷' },
  { id: 'sunglasses', label: 'Faces',      icon: '😎' },
  { id: 'tape',       label: 'Aesthetic',  icon: '📌' },
  { id: 'birthday',   label: 'Birthday',   icon: '🎂' },
  { id: 'wedding',    label: 'Wedding',    icon: '💍' },
  { id: 'festival',   label: 'Festival',   icon: '🪔' },
  { id: 'anime',      label: 'Anime',      icon: '⛩️' },
  { id: 'food',       label: 'Food',       icon: '🍕' },
  { id: 'animals',    label: 'Animals',    icon: '🐱' },
];
